import type { Metadata } from "next";
import { Geist, Geist_Mono,  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

 



export const metadata: Metadata = {
  title: "Garden Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body
        className={` antialiased max-w-[1440px] mx-auto overflow-x-hidden`}
      >
        <div>
          <Navbar/>
        </div>
        {children}
      </body>
    </html>
  );
}
