import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from 'next/font/local';

const cunia = localFont({
  src: './fonts/cunia.ttf',
  display: 'swap',
  variable: '--font-cunia',
})



export const metadata: Metadata = {
  title: "Garden Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body
        className={`${cunia.variable} antialiased max-w-[1440px] mx-auto overflow-x-hidden`}
      >
        <div>
          <Navbar/>
        </div>
        {children}
      </body>
    </html>
  );
}
